// The grammar of the code Fagi writes on her own.
//
// A rule is a data object, never a function: that's why it can be
// printed as a line of real JavaScript (`rule('id', {...})`) and read back
// without `eval`, just with a regular expression and `JSON.parse`. `rule()` is
// the only gatekeeper: it validates the shape before letting it in, whether
// the learner writes it (synth.js) or an imported file brings it.

import { modernKey, modernize } from '../legacy.js';

const SCOPES = ['eat', 'store', 'pursue'];
const VERDICTS = ['avoid', 'prefer'];
const STAGE_NAMES = ['short', 'medium', 'long'];
const VALID_ID = /^[a-z0-9-]{1,64}$/;
const CUE_FORM = /^[a-z]{1,20}:[a-z]{1,20}$/;

function fail(msg) {
  throw new Error(`invalid rule: ${msg}`);
}

function isNumber(v) {
  return typeof v === 'number' && Number.isFinite(v);
}

function validateBecause(because) {
  if (!Array.isArray(because)) fail('"because" must be a list');
  if (because.length > 12) fail('"because" has too many sensations');
  for (const s of because) {
    if (!s || typeof s.sense !== 'string' || s.sense.length > 40) fail('sensation without a valid "sense"');
    if (!isNumber(s.v)) fail('sensation without a numeric "v"');
  }
}

// rule(id, spec) → the validated rule, or throws with a readable reason.
// spec: { on, when:{key}, verdict, weight, because, learnedAt, revisedAt?,
//         tries, stage, retired?, retiredAt? }
export function rule(id, spec) {
  if (typeof id !== 'string' || !VALID_ID.test(id)) fail(`id "${id}" is malformed`);
  if (!spec || typeof spec !== 'object') fail('the rule body is missing');

  const { on, when, verdict, weight, because, learnedAt, revisedAt, tries, stage, retired, retiredAt, ...rest } = spec;
  const extra = Object.keys(rest);
  if (extra.length) fail(`unknown fields: ${extra.join(', ')}`);

  if (!Array.isArray(on) || on.length === 0 || on.some((a) => !SCOPES.includes(a))) {
    fail(`"on" must be a non-empty list within ${SCOPES.join('|')}`);
  }
  // About a species ({ key }) or about a trait ({ cue: 'smell:sour' }), never both.
  const aboutKey = when && typeof when.key === 'string' && when.key && when.key.length <= 80;
  const aboutCue = when && typeof when.cue === 'string' && CUE_FORM.test(when.cue);
  if (!when || aboutKey === aboutCue) fail('"when" must have either a "key" or a "cue" (dimension:value)');
  if (!VERDICTS.includes(verdict)) fail(`"verdict" must be ${VERDICTS.join('|')}`);
  if (!isNumber(weight)) fail('"weight" must be numeric');
  validateBecause(because);
  if (!isNumber(learnedAt)) fail('"learnedAt" must be numeric');
  if (revisedAt !== undefined && !isNumber(revisedAt)) fail('"revisedAt" must be numeric');
  if (!Number.isInteger(tries) || tries < 0) fail('"tries" must be an integer ≥ 0');
  if (!STAGE_NAMES.includes(stage)) fail(`"stage" must be ${STAGE_NAMES.join('|')}`);
  if (retired !== undefined && typeof retired !== 'boolean') fail('"retired" must be a boolean');
  if (retiredAt !== undefined && !isNumber(retiredAt)) fail('"retiredAt" must be numeric');

  return {
    id, on: [...on], when: aboutKey ? { key: when.key } : { cue: when.cue }, verdict, weight,
    because: because.map((s) => ({ sense: s.sense, v: s.v })),
    learnedAt, ...(revisedAt !== undefined ? { revisedAt } : {}),
    tries, stage,
    ...(retired ? { retired: true, retiredAt: retiredAt ?? learnedAt } : {}),
  };
}

// One line of code per rule. No commas or pretty formatting: the object is
// valid JSON, so it re-imports with JSON.parse without touching `eval`.
export function renderRule(r) {
  const { id, ...rest } = r;
  const line = `rule('${id}', ${JSON.stringify(rest)})`;
  return r.retired ? `// retired ${r.retiredAt.toFixed(1)}s: ${line}` : line;
}

const RULE_LINE = /^(?:\/\/ (?:retired|retirada) [\d.]+s: )?rule\('([a-z0-9-]{1,64})',\s*(\{.*\})\)$/;
const MEMORY_LINE = /^export const (?:memory|memoria) = (\{.*\});$/;

// The complete module, exactly as it's exported and shown in the panel.
export function renderModule(rules, facts, { age, puddleLife = null, synapses = null, cues = null } = {}) {
  const activeOnes = rules.filter((r) => !r.retired);
  const retiredList = rules.filter((r) => r.retired);
  const header = `// Code learned by Fagi · age ${(age ?? 0).toFixed(1)}s · ` +
    `${activeOnes.length} active rule(s), ${retiredList.length} retired\n` +
    `// Generated by src/learned/dsl.js. Imported without eval: each line is JSON.\n`;
  const body = [...activeOnes, ...retiredList].map((r) => '  ' + renderRule(r)).join(',\n');
  const rulesLine = body ? `export default [\n${body},\n];` : 'export default [];';
  // Besides the beliefs, what she knows about how the world is (how long a
  // puddle lasts) and what each thing made her feel (the concept→sensation synapses).
  // It's the same as what autosave stores: exporting and importing loses nothing.
  const memoryOf = { facts };
  if (puddleLife != null) memoryOf.puddleLife = Math.round(puddleLife * 10) / 10;
  if (synapses && Object.keys(synapses).length) memoryOf.synapses = synapses;
  if (cues && Object.keys(cues).length) {
    memoryOf.cues = Object.fromEntries(Object.entries(cues).map(([c, e]) => [c, { w: Math.round(e.w * 1000) / 1000, n: e.n }]));
  }
  const memoryLine = `export const memory = ${JSON.stringify(memoryOf)};`;
  return `${header}import { rule } from './dsl.js';\n\n${rulesLine}\n${memoryLine}\n`;
}

// Reads a generated module and returns { rules, facts }. It never executes the text:
// it looks for lines with the exact shape of renderRule/renderModule and validates each
// one with rule(). Anything that doesn't fit is ignored or fails the
// whole import, depending on the case.
export function parseModule(text) {
  if (typeof text !== 'string') throw new Error('the module must be text');
  if (text.length > 256 * 1024) throw new Error('the module is too large');

  const rules = [];
  let facts = {};
  let puddleLife = null;
  let synapses = {};
  let cues = {};
  let seenMemory = false;

  for (const line of text.split('\n')) {
    // renderModule separates the rules with list commas (one per line, the
    // last one included); it's stripped so the exact `rule(...)` remains.
    const l = line.trim().replace(/,\s*$/, '');
    if (!l) continue;

    const m = RULE_LINE.exec(l);
    if (m) {
      const [, id, json] = m;
      let spec;
      try { spec = JSON.parse(json); } catch { throw new Error(`rule line with invalid JSON: ${l.slice(0, 60)}`); }
      rules.push(rule(modernKey(id), modernize(spec)));
      continue;
    }

    const mm = MEMORY_LINE.exec(l);
    if (mm) {
      let data;
      try { data = modernize(JSON.parse(mm[1])); } catch { throw new Error('the memory line has invalid JSON'); }
      if (data && typeof data === 'object' && data.facts && typeof data.facts === 'object') {
        facts = data.facts;
        if (typeof data.puddleLife === 'number' && Number.isFinite(data.puddleLife) && data.puddleLife > 0) {
          puddleLife = data.puddleLife;
        }
        synapses = validateSynapses(data.synapses);
        cues = validateCues(data.cues);
        seenMemory = true;
      }
    }
    // Any other line (comments, import, export default [ ... ]) is ignored.
  }

  if (!seenMemory && rules.length === 0) throw new Error('no rule or memory recognized in the file');
  return { rules, facts, puddleLife, synapses, cues };
}

// Only well-formed traits get in: 'dimension:value' with a weight in [-1, 1].
function validateCues(cues) {
  const out = {};
  if (!cues || typeof cues !== 'object') return out;
  for (const [c, e] of Object.entries(cues).slice(0, 200)) {
    if (!CUE_FORM.test(c) || !e || !isNumber(e.w) || e.w < -1 || e.w > 1) continue;
    out[c] = { w: e.w, n: Number.isInteger(e.n) && e.n >= 0 ? e.n : 0, lastAt: 0 };
  }
  return out;
}

// Only well-formed concept→sensation connections get in; the rest is ignored.
function validateSynapses(syn) {
  const outside = {};
  if (!syn || typeof syn !== 'object') return outside;
  for (const [id, s] of Object.entries(syn).slice(0, 500)) {
    if (!s || typeof s !== 'object') continue;
    const { a, b, w, n } = s;
    if (typeof a !== 'string' || typeof b !== 'string' || a.length > 80 || b.length > 80) continue;
    if (id !== `${a}>${b}` || !a.startsWith('key:') || !b.startsWith('feel:')) continue;
    if (!isNumber(w) || w < -1 || w > 1) continue;
    outside[id] = { a, b, kind: 'feel', w, n: isNumber(n) ? n : 0 };
  }
  return outside;
}
