// What the page's scripts write, in each language the page comes in. The
// prose is in the HTML of each language; this is only what JS draws.
const ES = {
  formats: { none: 'nada', verdict: 'veredictos', rule: 'razones', evidence: 'razones + evidencia' },
  formatsShort: { none: 'nada', verdict: 'veredictos', rule: 'razones', evidence: '+ evidencia' },
  less: 'menos es mejor', more: 'más es mejor',
  harmTitle: 'Bocados dañinos por hormiga, mundo estable',
  survTitle: 'Supervivientes en la generación de la inversión',
  mythTitle: 'Mitos por hormiga al llegar la inversión',
  labSource: 'Laboratorio · 200 linajes por celda',
  gameSource: 'Juego completo · 75 linajes por formato',
  generation: 'generación', change: 'cambio',
  curves: { alive: 'Supervivientes por hormiga', myths: 'Mitos por hormiga (falsos y nunca vividos)', harmful: 'Bocados dañinos por hormiga', acc: 'Precisión de lo que se enseña al nacer' },
  running: 'Corriendo…', run: 'Correr los 4 formatos', ran: (ms) => `4 linajes en ${ms} ms, en tu navegador`,
  carriers: 'hormigas la llevan', isFalse: 'falsa en ese mundo', empty: 'Ninguna creencia pasó de hormiga a hormiga.',
  beliefs: (n, f) => `${n} creencias transmitidas con «${f}»; se muestran las más longevas`,
  summary: (f, a, m) => `${f}: ${a} de supervivientes en la generación 6 · ${m} mitos por hormiga`,
  inheritTitle: 'Vivas a las 2 horas, por generación · programa con «volver al anochecer» al final',
  genShort: 'g', slot: 'vida', alive: 'viva', dead: 'murió', carries: 'lleva la línea que repara', motherWord: 'hija de la vida',
  ofPops: (n) => `de ${n}`,
  pedStats: (a, n, r, intact) => `vivas en g3–5: ${a}/${n} · ${intact ? 'con alguna regla' : 'llevan la reparación'}: ${r}`,
  explorerNote: (d) => ({
    dusk: 'Con «volver al anochecer» al final. Las que aprenden solas escriben la reparación tarde o nunca; las que heredan nacen con ella y desde la generación 2 casi todas la llevan. Por defecto se muestra la población más cercana a la media del estudio.',
    shelter: 'Con «refugiarse» al final. Aprender en vida apenas cambia nada; la reparación se extiende por herencia. Por defecto, la población más cercana a la media del estudio.',
    intact: 'Programa intacto: no hay nada que reparar. Las que aprenden escriben reglas que no necesitaban; las que heredan nacen con las de su madre, y mueren más. Por defecto, la población más cercana a la media del estudio.',
  })[d],
  inherit2Title: 'Vivas a las 2 horas, generaciones 3–5 · segundo estudio (9 oct)',
  damages: ['«volver al anochecer» al final', '«refugiarse» al final', 'programa intacto'],
  arms: { born: 'innato', learn: 'aprende', inheritAny: 'hereda de cualquiera', inherit: 'hereda de supervivientes' },
  calibTitle: 'Vivas a las 2 horas según cada cuánto da fruto un árbol',
  calibX: 'segundos entre frutos', calibMark: 'mundo de prueba',
  calib: { born: 'innato', noWarmth: 'sin calor', noFood: 'sin comida', learns: 'aprende' },
  coverageTitles: ['Supervivencia y enseñanza · diferencia', 'Mitos por hormiga · diferencia'],
  coverageSeries: ['contando elementos', 'igualando cobertura'],
  coverageGroups: ['trampa en la inversión (veredictos − razones)', 'ventaja de las razones para enseñar', 'mitos de más con razones', 'mitos que corta la evidencia'],
  habitats: { cold: 'frío', hot: 'cálido', toxic: 'venenoso' },
  genes: { muscle: 'músculo', brain: 'cerebro', size: 'tamaño' },
  evoTitle: (g) => `Gen de ${g} de las vivas, media de 8 mapas · 1 = fundadoras`,
  year: 'año',
  tpTitle: 'Crías por hormiga según dónde nació, en el nido donde se crió',
  tpSeries: ['nacidas allí', 'traídas de otro nido'],
  clipClose: 'Cerrar',
};

const EN = {
  formats: { none: 'nothing', verdict: 'verdicts', rule: 'reasons', evidence: 'reasons + evidence' },
  formatsShort: { none: 'nothing', verdict: 'verdicts', rule: 'reasons', evidence: '+ evidence' },
  less: 'lower is better', more: 'higher is better',
  harmTitle: 'Harmful bites per ant, steady world',
  survTitle: 'Survivors in the generation of the inversion',
  mythTitle: 'Myths per ant going into the inversion',
  labSource: 'Lab · 200 lineages per cell',
  gameSource: 'Full game · 75 lineages per format',
  generation: 'generation', change: 'change',
  curves: { alive: 'Survivors per ant', myths: 'Myths per ant (false and never lived)', harmful: 'Harmful bites per ant', acc: 'Accuracy of what newborns are taught' },
  running: 'Running…', run: 'Run all 4 formats', ran: (ms) => `4 lineages in ${ms} ms, in your browser`,
  carriers: 'ants carry it', isFalse: 'false in that world', empty: 'No belief went from ant to ant.',
  beliefs: (n, f) => `${n} beliefs passed on with “${f}”; the longest-lived are shown`,
  summary: (f, a, m) => `${f}: ${a} survivors in generation 6 · ${m} myths per ant`,
  inheritTitle: 'Alive at 2 hours, by generation · program with “go home at dusk” moved last',
  genShort: 'g', slot: 'life', alive: 'alive', dead: 'died', carries: 'carries the repairing line', motherWord: 'daughter of life',
  ofPops: (n) => `of ${n}`,
  pedStats: (a, n, r, intact) => `alive in g3–5: ${a}/${n} · ${intact ? 'with some rule' : 'carry the repair'}: ${r}`,
  explorerNote: (d) => ({
    dusk: '“Go home at dusk” moved last. Daughters learning alone write the repair late or never; inheriting daughters are born with it, and from generation 2 almost all carry it. By default, the population closest to the study\'s mean.',
    shelter: '“Take shelter” moved last. Learning within a life barely changes anything; the repair spreads through inheritance. By default, the population closest to the study\'s mean.',
    intact: 'Intact program: nothing to repair. Daughters that learn write rules they did not need; inheriting daughters are born with their mother\'s, and die more. By default, the population closest to the study\'s mean.',
  })[d],
  inherit2Title: 'Alive at 2 hours, generations 3–5 · second study (9 Oct)',
  damages: ['“go home at dusk” moved last', '“take shelter” moved last', 'intact program'],
  arms: { born: 'born', learn: 'learns', inheritAny: 'inherits from any', inherit: 'inherits from survivors' },
  calibTitle: 'Alive at 2 hours by how often a tree bears fruit',
  calibX: 'seconds between fruit', calibMark: 'test world',
  calib: { born: 'innate', noWarmth: 'no warmth', noFood: 'no food', learns: 'learns' },
  coverageTitles: ['Survival and teaching · difference', 'Myths per ant · difference'],
  coverageSeries: ['counting items', 'matching coverage'],
  coverageGroups: ['trap at the inversion (verdicts − reasons)', 'reasons\' teaching edge', 'extra myths with reasons', 'myths evidence cuts'],
  habitats: { cold: 'cold', hot: 'hot', toxic: 'toxic' },
  genes: { muscle: 'muscle', brain: 'brain', size: 'size' },
  evoTitle: (g) => `${g[0].toUpperCase()}${g.slice(1)} gene of the living, mean of 8 maps · 1 = founders`,
  year: 'year',
  tpTitle: 'Offspring per ant by where she was born, in the nest that raised her',
  tpSeries: ['born there', 'brought from another nest'],
  clipClose: 'Close',
};

export const LANG = document.documentElement.lang === 'en' ? 'en' : 'es';
export const T = LANG === 'en' ? EN : ES;
export const pct = (v) => `${Math.round(v * 100)}%`;
export const num = (v, d = 2) => (LANG === 'en' ? v.toFixed(d) : v.toFixed(d).replace('.', ','));
